---
- name: Install nginx
  pacman:
    name: nginx
    state: installed

- name:  Create root directory
  file:
    path: "{{ nginx_root_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure nginx
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/{{ item }}"
    backup: yes
    owner: root
    group: root
    mode: 0644
  loop:
    - nginx.conf
  notify:
    - Restart nginx
