---
- name: Install go, go-tools
  tags: golang
  aur:
    skip_installed: yes
    name:
      - go
      - go-tools

- name: Install golang helpers
  tags: golang
  command:
    go get -u {{ item }}
  register: goget_result
  changed_when: goget_result.stderr != ""
  loop:
    - github.com/nsf/gocode
    - github.com/rogpeppe/godef
    - golang.org/x/tools/cmd/guru
    - golang.org/x/tools/cmd/gorename
    - golang.org/x/tools/cmd/goimports
    - github.com/zmb3/gogetdoc
    - github.com/godoctor/godoctor
    - github.com/fatih/gomodifytags
    - github.com/alecthomas/gometalinter
    - golang.org/x/tour/gotour

- name: Setup gometalinter
  tags: golang
  command:
    go/bin/gometalinter --install
  ignore_errors: yes
