---
- name: Install go, go-tools
  tags: golang
  aur:
    skip_installed: yes
    name:
      - go
      - go-tools

- name: Install golang helpers
  tags: golang
  command:
    go get -u {{ item }}
  register: goget_result
  changed_when: goget_result.stderr != ""
  loop:
    - github.com/mdempsky/gocode
    - github.com/rogpeppe/godef
    - golang.org/x/tools/cmd/guru
    - golang.org/x/tools/cmd/gorename
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/cmd/godoc
    - github.com/zmb3/gogetdoc
    - github.com/cweill/gotests/...
    - github.com/haya14busa/gopkgs/cmd/gopkgs
    - github.com/davidrjenni/reftools/cmd/fillstruct
    - github.com/josharian/impl
    - github.com/golangci/golangci-lint/cmd/golangci-lint
    - github.com/godoctor/godoctor
    - github.com/fatih/gomodifytags
    - golang.org/x/tour
