# Copyright © 2019 4km3
# https://github.com/orgs/4km3/people

#   This file is part of archify.

#   archify is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   archify is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with archify.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install fish and time
  tags: fish
  aur:
    skip_installed: yes
    name:
      - fish
      - time

- name: Add ~/.local/bin, ~/go/bin to PATH
  tags: fish
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/fish/conf.d/{{ item }}
  loop:
    - homebin.fish
    - gobin.fish

- name: Create dir for fish config
  tags: fish
  file:
    path: "{{ ansible_user_dir }}/.config/fish/functions"
    state: directory

- name: Configure fish
  tags: fish
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.config/fish/{{ item }}"
  loop:
    - config.fish

- name: Configure fish prompt
  tags: fish
  copy:
    remote_src: yes
    src: /usr/share/fish/tools/web_config/sample_prompts/terlar.fish
    dest: "{{ ansible_user_dir }}/.config/fish/functions/fish_prompt.fish"

- name: Use simple prompt if TERM=dumb for emacs' tramp to function ok
  tags: fish
  blockinfile:
    path: "{{ ansible_user_dir }}/.config/fish/functions/fish_prompt.fish"
    insertafter: set -l last_status \$status
    block: |2
          if test $TERM = dumb
              echo -n '$ '
              return
          end

- name: Fix prompt character for clarity
  tags: fish
  lineinfile:
    path: "{{ ansible_user_dir }}/.config/fish/functions/fish_prompt.fish"
    regexp: echo -n '➤ '
    line: |2
          echo -n '▶ '

- name: Set fish as default shell for main user
  tags: fish
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
