---
- name: Update /etc/mkinitcpio.conf
  tags: initcpio
  become: yes
  template:
    dest: "/etc/{{ item }}"
    src: "{{ item }}.j2"
    backup: yes
  loop:
    - mkinitcpio.conf
  notify:
    - Regenerate initcpio
