---
- name: Enable xz compression for mkinitcpio
  lineinfile:
    dest=/etc/mkinitcpio.conf
    backup=yes
    state=present
    backrefs=yes 
    regexp='^#?(COMPRESSION="xz")'
    line='\1'
  notify:
    - Regenerate initcpio

# Alternate way, more verbose;  Thanks Virgy for giving me feedback on the two alts!
#    regexp='^#?(?P<compression_method>COMPRESSION="xz")'
#    line='\g<compression_method>'

