---
- name: Update /etc/mkinitcpio.conf
  template:
    dest=/etc/{{ item }}
    src={{ item }}.j2
    backup=yes
  with_items:
    - mkinitcpio.conf
  notify:
    - Regenerate initcpio
  tags:
    - initcpio
