---
- name: Install iw and get rid of deprecated and/or unneeded stuff
  tags: systemd-networkd
  become: yes
  pacman:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { name: iw,                     state: present  }
    - { name: wireless_tools,         state: absent   }
    - { name: netctl,                 state: absent   }
    - { name: dhcpcd,                 state: absent   }
    - { name: openresolv,             state: absent   }
    - { name: systemd-resolvconf,     state: present  }

- name: Configure wl* and en*
  tags: systemd-networkd
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/network/{{ item }}
  loop:
    - 10-wl.network
    - 10-en.network
  notify:
    - Restart systemd-networkd

- name: Enable and start systemd-networkd
  tags: systemd-networkd
  become: yes
  systemd:
    name: systemd-networkd
    enabled: yes
    state: started
