---
- name: Install iw and get rid of deprecated and/or unneeded stuff
  pacman:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: iw,             state: present }
    - { name: wireless_tools, state: absent  }
    - { name: netctl,         state: absent  }
    - { name: dhcpcd,         state: absent  }
    - { name: openresolv,     state: absent  }

- name: Configure wl* and en*
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/network/{{ item }}
  with_items:
    - 10-wl.network
    - 10-en.network
  notify:
    - Reload systemd-networkd

- name: Enable and start systemd-networkd
  service:
    name: systemd-networkd
    enabled: yes
    state: started
