---
- name: Install iw and remove wireless_tools
  pacman:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: iw, state: present }
    - { name: wireless_tools, state: absent }

- name: Configure wlan0 and eth0
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/network/{{ item }}
  with_items:
    - 10-dhcp.network
    - 10-eth.network
  notify:
    - Reload systemd-networkd

- name: Enable and start systemd-networkd
  service:
    name: systemd-networkd
    enabled: yes
    state: started
