---
- name: Copy /etc/hostname
  tags: hostname
  become: yes
  copy:
    content: "{{ hostname }}\n"
    dest: /etc/hostname
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify:
    - Set hostname
