---
- name: Install Solarized Xresources file
  git:
    repo: "{{ solarized_repo }}"
    dest: /opt/solarized/xresources
    force: yes
  tags:
    - solarized

- name: Reduce fading
  tags: fading
  lineinfile:
    dest: /opt/solarized/xresources/Xresources.dark
    state: present
    regexp: '^\*fading:'
    line: '*fading:                15'
