---
- name: Install Solarized Xresources file
  tags: solarized
  become: yes
  git:
    repo: "{{ solarized_repo }}"
    dest: /opt/solarized/xresources
    force: yes

- name: Reduce fading
  tags: solarized
  become: yes
  lineinfile:
    dest: /opt/solarized/xresources/Xresources.dark
    state: present
    regexp: '^\*fading:'
    line: '*fading:                15'
