---
- name: Install Wolfgang Rosenauer GPG key
  tags: pamssh
  command:
    gpg --keyserver hkp://eu.pool.sks-keyservers.net --recv-keys 180F6A5B3EDE742E
  register: gpg_output
  until: gpg_output is success
  retries: 500

- name: Install pam_ssh
  tags: pamssh
  aur:
    skip_installed: yes
    name: pam_ssh

- name: Enable pam_ssh for XDM
  tags: pamssh
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/pam.d/{{ item }}
    backup: yes
  loop:
    - xdm
