---
- name: Install Wolfgang Rosenauer GPG key
  tags: pamssh
  become: no
  command: >
    gpg --keyserver hkp://eu.pool.sks-keyservers.net --recv-keys 180F6A5B3EDE742E
  register: gpg_output
  until: gpg_output | success
  retries: 5

- name: Install pam_ssh
  tags: pamssh
  command: >
    yaourt --noconfirm -S pam_ssh
  register: yaourt_result
  changed_when: yaourt_result.stderr != ""
  become: no

- name: Enable pam_ssh for XDM
  tags: pamssh
  template:
    src: "{{ item }}.j2"
    dest: /etc/pam.d/{{ item }}
    backup: yes
  with_items:
    - xdm
