---
- name: Install Wolfgang Rosenauer GPG key
  sudo: no
  action:
    module: command
      gpg --recv-keys 180F6A5B3EDE742E
  register: gpg_output
  until: gpg_output | success
  retries: 5


- name: Install pam_ssh
  command:
    yaourt --noconfirm -S pam_ssh
  register: yaourt_result
  changed_when: "yaourt_result.stderr != ''"
  sudo: no
  tags:
    - pamssh


- name: Enable pam_ssh for XDM
  template:
    src={{ item }}.j2
    dest=/etc/pam.d/{{ item }}
    backup=yes
    owner=root
    group=root
    mode=0644
  with_items:
    - xdm
