---
- name: Install pam_ssh
  command:
    yaourt --noconfirm -S pam_ssh
  register: yaourt_result
  changed_when: "yaourt_result.stderr != ''"
  sudo: no


- name: Enable pam_ssh for XDM
  template:
    src={{ item }}.j2
    dest=/etc/pam.d/{{ item }}
    backup=yes
    owner=root
    group=root
    mode=0644
  with_items:
    - xdm
