---
# TODO: according to arch wiki, ifplugd functionality is now provided by dhcpcd out of the box
# See how can we get rid of ifplugd, then


- name: Install ifplugd
  pacman:
    name=ifplugd
    state=installed


- name: Install wired netctl profiles
  copy:
    src={{ item }}
    dest=/etc/netctl/{{ item | basename }}
    backup=yes
    owner=root
    group=root
    mode=0640
  with_fileglob: "wired-profiles/*"


- name: Enable netctl-ifplugd@eth0 service
  command:
    systemctl enable netctl-ifplugd@eth0 
  register: systemctl_result
  changed_when: "systemctl_result.stderr != ''"


- name: Start netctl-ifplugd@eth0 service
  command:
    systemctl start netctl-ifplugd@eth0 
  register: systemctl_result
  changed_when: "systemctl_result.stderr != ''"


# FIXME: eth0 suffix gets lost
#- name: Start netctl-ifplugd@eth0 service
#  service:
#    name=netctl-ifplugd@eth0
#    state=started
