---
- name: Install XDM
  pacman:
    name: xorg-xdm

- name: Install xdm-minimalist
  become: no
  aur:
    name: xdm-minimalist
    skip_installed: yes

- name: Copy Xresources to /etc/X11/xdm
  template:
    src: "{{ item }}.j2"
    dest: /etc/X11/xdm/{{ item }}
    backup: yes
    owner: root
    group: root
    mode: 0644
  loop:
    - Xresources

- name: Secure Xservers
  lineinfile:
    dest: /etc/X11/xdm/Xservers
    backup: yes
    backrefs: yes
    regexp: '^(:0 local /usr/bin/X) (:0)'
    line: '\1 -nolisten tcp \2'

- name: Enable XDM-minimalist
  service:
    name: xdm-minimalist
    enabled: yes
