---
- name: Install XDM and xdm-minimalist
  tags: xdm
  aur:
    skip_installed: yes
    name:
      - xorg-xdm
      - xdm-minimalist

- name: Copy Xresources to /etc/X11/xdm
  tags:
    - xdm
    - xresources
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/X11/xdm/{{ item }}
    backup: yes
    owner: root
    group: root
    mode: 0644
  loop:
    - Xresources

- name: Secure Xservers
  tags: xdm
  become: yes
  lineinfile:
    dest: /etc/X11/xdm/Xservers
    backup: yes
    backrefs: yes
    regexp: '^(:0 local /usr/bin/X) (:0)'
    line: '\1 -nolisten tcp \2'

- name: Enable XDM-minimalist
  tags: xdm
  become: yes
  systemd:
    name: xdm-minimalist
    enabled: yes
