---
- name: Install xbindkeys
  tags: xbindkeys
  become: no
  aur:
    skip_installed: yes
    name: xbindkeys

- name: Enable xbindkeys in xinitrc.d
  tags: xbindkeys
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/X11/xinit/xinitrc.d/{{ item }}
    owner: root
    group: root
    mode: 0755
  loop:
    - 80-xbindkeys.sh

- name: Gather facts to refresh ansible_env
  tags: xbindkeys
  become: no
  setup:

- name: Configure xbindkeys
  tags: xbindkeys
  become: no
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  loop:
    - .xbindkeysrc
