- name: Install ddclient
  pacman:
    name: ddclient
  tags:
    - ddclient

- name: Config ddclient
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ddclient/{{ item }}"
    mode: 600
    owner: root
    group: root
  with_items:
    - ddclient.conf
  notify:
    - Restart ddclient
  tags:
    - ddclient

- name: Enable and start ddclient service
  service:
    name: ddclient
    enabled: yes
    state: started
  tags:
    - ddclient
