- name: Install ddclient
  tags: ddclient
  become: no
  aur:
    skip_installed: yes
    name: ddclient

- name: Config ddclient
  tags: ddclient
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ddclient/{{ item }}"
    mode: 600
    owner: root
    group: root
  loop:
    - ddclient.conf
  notify:
    - Restart ddclient

- name: Enable and start ddclient service
  tags: ddclient
  become: yes
  service:
    name: ddclient
    enabled: yes
    state: started
