---
- name: Install OpenSSH
  pacman:
    name=openssh
    state=installed


- name: Configure OpenSSH
  lineinfile:
    dest=/etc/ssh/sshd_config
    backup=yes
    insertafter='^#PasswordAuthentication yes'
    regexp='^PasswordAuthentication'
    line='PasswordAuthentication no'
  notify:
    - Restart OpenSSH


- name: Start OpenSSH
  service:
    name=sshd
    state=started
    enabled=yes
