---
- name: Install libvirt and friends
  tags: libvirt
  pacman:
    name:
      - libvirt
      - virt-manager
      - virt-viewer
      - bridge-utils
      - dnsmasq
      - openbsd-netcat
      - qemu
      - qemu-guest-agent
      - ovmf
      - ebtables
      - dmidecode

- name: Config qemu - root user
  tags: libvirt
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    backup: yes
    backrefs: yes
    state: present
    regexp: '^#?(user = "root")'
    line: '\1'

- name: Config qemu - UEFI settings
  tags: libvirt
  blockinfile:
    dest: /etc/libvirt/qemu.conf
    backup: yes
    insertbefore: "#nvram = \\["
    block: |
      nvram = [
          "/usr/share/ovmf/x64/OVMF_CODE.fd:/usr/share/ovmf/x64/OVMF_VARS.fd"
      ]

- name: Install polkit rules file
  tags: libvirt
  template:
    src: "{{ item }}.j2"
    dest: /etc/polkit-1/rules.d/{{ item }}
    backup: yes
    owner: root
    group: root
    mode: 0644
  loop:
    - 50-org.libvirt.unix.manage.rules

- name: Enable libvirtd and libvirt-guests
  tags: libvirt
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - libvirtd
    - libvirt-guests

- name: Add main user to group kvm
  tags: libvirt
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: kvm
