---
- name: Install libvirt, virt-manager, bridge-utils, openbsd-netcat, qemu, ebtables and dmidecode
  tags: libvirt
  pacman:
    name: "{{ item }}"
    state: installed
  with_items:
    - libvirt
    - virt-manager
    - bridge-utils
    - openbsd-netcat
    - qemu
    - ebtables
    - dmidecode

- name: Config qemu
  tags: libvirt
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    backup: yes
    backrefs: yes
    state: present
    regexp: '^#?(user = "root")'
    line: '\1'

- name: Install polkit rules file
  tags: libvirt
  template:
    src: "{{ item }}.j2"
    dest: /etc/polkit-1/rules.d/{{ item }}
    backup: yes
    owner: root
    group: root
    mode: 0644
  with_items:
    - 50-org.libvirt.unix.manage.rules

- name: Enable libvirtd and libvirt-guests
  tags: libvirt
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - libvirtd
    - libvirt-guests

- name: Add main user to group kvm
  tags: libvirt
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: kvm
