---
- name: Install emacs and poppler
  tags: spacemacs
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - emacs
    - poppler
    - poppler-glib

- name: Gather facts to refresh ansible_env
  tags: spacemacs
  become: no
  setup:

- name: Clone Spacemacs
  tags: spacemacs
  become: no
  git:
    repo: "{{ spacemacs_repo }}"
    dest: "{{ ansible_user_dir }}/.emacs.d"

- name: Configure Spacemacs
  tags: spacemacs
  become: no
  template:
    force: no
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .spacemacs
