# Copyright © 2019 4km3
# https://github.com/orgs/4km3/people

#   This file is part of archify.

#   archify is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   archify is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with archify.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install emacs and dependencies
  tags: spacemacs
  aur:
    name:
      - emacs
      - ctags
      - aspell-en
      - hunspell-en_US
      - bdf-unifont
      - jupyter
      - poppler
      - poppler-glib
      - python-black
      - python-pytest
      - ripgrep
      - yapf
      - global
      - nodejs-tern
      - nodejs-vmd
      - python-autoflake
      - python-epc
      - python-importmagic
      - python-language-server
      - python-ptvsd
      - python-pyls-isort-git
      - pyls-mypy
      - flake8
      - shellcheck
      - bashate

- name: Clone Spacemacs
  tags: spacemacs
  git:
    repo: "{{ spacemacs_repo }}"
    version: "{{ spacemacs_branch }}"
    dest: "{{ ansible_user_dir }}/.emacs.d"
  ignore_errors: yes

- name: Patch Spacemacs
  tags: spacemacs
  patch:
    src: pdf-view-fix-colors.patch
    basedir: "{{ ansible_user_dir }}/.emacs.d"
    strip: 1

- name: Create ~/.spacemacs.d config dir
  tags: spacemacs
  file:
    state: directory
    path: "{{ ansible_user_dir }}/{{ spacemacs_dotdir }}"

- name: Configure Spacemacs
  tags: spacemacs
  template:
    force: no
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ spacemacs_dotdir }}/{{ item }}"
  loop:
    - init.el

- name: Install packages
  tags: spacemacs
  command:
    emacs --batch --load={{ ansible_user_dir }}/.emacs.d/init.el
  args:
    stdin: "y\n"
  ignore_errors: yes
