---
- name: Install emacs and poppler
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - emacs
    - poppler
    - poppler-glib
  tags:
    - spacemacs

- name: Gather facts to refresh ansible_env
  become: no
  setup:
  tags:
    - spacemacs

- name: Clone Spacemacs
  become: no
  git:
    repo: "{{ spacemacs_repo }}"
    dest: "{{ ansible_user_dir }}/.emacs.d"
  tags:
    - spacemacs

- name: Configure Spacemacs
  become: no
  template:
    force: no
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .spacemacs
  tags:
    - spacemacs
