---
- name: Install emacs and dependencies
  tags: spacemacs
  become: yes
  pacman:
    name:
      - emacs
      - ctags
      - aspell-en
      - hunspell-en_US
      - bdf-unifont
      - poppler
      - poppler-glib
      - python-black
      - python-pytest
      - ripgrep
      - yapf

- name: Gather facts to refresh ansible_env
  tags: spacemacs
  become: no
  setup:

- name: Install dependencies
  tags: spacemacs
  become: no
  aur:
    skip_installed: yes
    name:
      - global
      - nodejs-tern
      - nodejs-vmd
      - python-autoflake
      - python-epc
      - python-importmagic
      - python-language-server
      - python-ptvsd
      - python-pyls-isort-git
      - pyls-mypy
      - flake8

- name: Clone Spacemacs
  tags: spacemacs
  become: no
  git:
    repo: "{{ spacemacs_repo }}"
    version: "{{ spacemacs_branch }}"
    dest: "{{ ansible_user_dir }}/.emacs.d"
  ignore_errors: yes

- name: Patch Spacemacs
  tags: spacemacs
  become: no
  patch:
    src: pdf-view-fix-colors.patch
    basedir: "{{ ansible_user_dir }}/.emacs.d"
    strip: 1

- name: Create ~/.spacemacs.d config dir
  tags: spacemacs
  become: no
  file:
    state: directory
    path: "{{ ansible_user_dir }}/{{ spacemacs_dotdir }}"

- name: Configure Spacemacs
  tags: spacemacs
  become: no
  template:
    force: no
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ spacemacs_dotdir }}/{{ item }}"
  loop:
    - init.el

- name: Install packages
  tags: spacemacs
  become: no
  command:
    emacs --batch --load={{ ansible_user_dir }}/.emacs.d/init.el
  args:
    stdin: "y\n"
  ignore_errors: yes
