---
- name: Install emacs, ctags, hunspell-en, bdf-unifont and poppler
  tags: spacemacs
  become: yes
  pacman:
    name:
      - emacs
      - ctags
      - hunspell-en
      - bdf-unifont
      - poppler
      - poppler-glib

- name: Gather facts to refresh ansible_env
  tags: spacemacs
  become: no
  setup:

- name: Install global and nodejs-tern
  tags: spacemacs
  become: no
  aur:
    skip_installed: yes
    name:
      - global
      - nodejs-tern

- name: Clone Spacemacs
  tags: spacemacs
  become: no
  git:
    repo: "{{ spacemacs_repo }}"
    version: "{{ spacemacs_branch }}"
    dest: "{{ ansible_user_dir }}/.emacs.d"
  failed_when: false

- name: Patch Spacemacs
  tags: spacemacs
  become: no
  patch:
    src: pdf-view-fix-colors.patch
    basedir: "{{ ansible_user_dir }}/.emacs.d"
    strip: 1

- name: Configure Spacemacs
  tags: spacemacs
  become: no
  template:
    force: no
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .spacemacs
