---
# tasks file for partition
- name: Clear SSD using blkdiscard
  tags: blkdiscard
  command:
    blkdiscard {{ main_block_device }}
  when: "'vda' not in main_block_device"

- name: Zap GPT and MBR
  tags: sgdisk
  command:
    sgdisk --zap-all {{ main_block_device }}

- name: Partition drive for EFI
  tags: sgdisk
  command:
    sgdisk  --new=0:0:+200M  --typecode=0:ef00 --change-name=0:'EFI System'
            --new=0:0:+8G    --typecode=0:8200 --change-name=0:swap
            --new=0:0:0      --typecode=0:8304 --change-name=0:root
            {{ main_block_device }}
