---
# tasks file for partition
- name: Clear SSD using blkdiscard
  become: no
  tags: blkdiscard
  command:
    blkdiscard {{ main_block_device }}
  when: "'vda' not in main_block_device"

- name: Zap GPT and MBR
  tags: sgdisk
  become: no
  command:
    sgdisk --zap-all {{ main_block_device }}

- name: Partition drive for EFI
  tags: sgdisk
  become: no
  command:
    sgdisk  --new=0:0:+200M  --typecode=0:ef00 --change-name=0:'EFI System'
            --new=0:0:+8G    --typecode=0:8200 --change-name=0:swap
            --new=0:0:0      --typecode=0:8304 --change-name=0:root
            {{ main_block_device }}

- name: Create ESP filesystem
  tags: filesystem
  become: no
  filesystem:
    dev: "{{ main_block_device_base }}1"
    fstype: vfat
    opts: -F32 -nESP
    force: yes

- name: Create swap volume
  become: no
  tags: mkswap
  command:
    mkswap -L swap {{ main_block_device_base }}2

- name: Create BTRFS filesystem
  tags: mkbtrfs
  become: no
  filesystem:
    dev: "{{ main_block_device_base }}3"
    fstype: btrfs
    force: yes
    opts: -L root
