---
# tasks file for partition
- name: Clear SSD using blkdiscard
  command: >
    blkdiscard {{ main_block_device }}

- name: Partition drive for EFI
  tags: sgdisk
  command: >
    sgdisk  -n 0:0:+200M  -t 0:ef00 -c 0:'EFI System'
            -n 0:0:+8G    -t 0:8200 -c 0:swap
            -n 0:0:0      -t 0:8304 -c 0:root
            {{ main_block_device }}

- name: Create ESP filesystem
  filesystem:
    dev: "{{ main_block_device_base }}1"
    fstype: vfat
    opts: -F32 -nESP

- name: Create swap volume
  command: >
    mkswap -L swap {{ main_block_device_base }}2

- name: Create BTRFS filesystem
  filesystem:
    dev: "{{ main_block_device_base }}3"
    fstype: btrfs
    force: yes
    opts: -L root
