---
- name: Gather facts to refresh ansible_env
  tags: xdg
  become: no
  setup:

- name: Create ~/.config/
  tags: xdg
  become: no
  file:
    path: "{{ ansible_user_dir }}/.config/"
    state: directory

- name: Configure user xdg
  tags: xdg
  become: no
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.config/{{ item }}"
  loop:
    - user-dirs.dirs
    - user-dirs.locale
