---
- name: Install intel-ucode
  tags: intel
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - intel-ucode

- name: Install rasdaemon
  tags: intel
  become: no
  command: >
    yaourt --noconfirm -S rasdaemon
