---
- name: Install termite terminal emulator
  tags: termite
  become: no
  aur:
    skip_installed: yes
    name: termite

- name: Configure termite
  tags: termite
  become: yes
  template:
    src: '{{ item }}.j2'
    dest: '/etc/xdg/termite/{{ item }}'
  loop:
    - config
