---
- name: Install pentadactyl
  tags:
    - pentadactyl
    - pentadactyl-pkg
  become: no
  aur:
    name: firefox-pentadactyl-signed
    skip_installed: yes

- name: Gather facts to refresh ansible_env
  tags:
    - pentadactyl
    - pentadactyl-cfg
  become: no
  setup:

- name: Install pentadactyl configuration files
  tags:
    - pentadactyl
    - pentadactyl-cfg
  become: no
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .pentadactylrc
