---
- name: Create ~/.ssh/login-keys.d/
  tags: credentials
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/.ssh/keys.d"
    - "{{ ansible_user_dir }}/.ssh/login-keys.d"
    - "{{ ansible_user_dir }}/.ssh/session-keys.d"

- name: Set credentials for main user
  tags: credentials
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    password: "{{ user_password | mandatory }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/keys.d/id_ed25519
    ssh_key_passphrase: "{{ user_passphrase | mandatory }}"

- name: Symlink ~/.ssh/login-keys.d/id_ed25519 to ~/.ssh/keys.d/id_ed25519
  tags: credentials
  file:
    src: "../keys.d/id_ed25519"
    path: "{{ ansible_user_dir }}/.ssh/login-keys.d/id_ed25519"
    state: link
