# Copyright © 2019 4km3
# https://github.com/orgs/4km3/people

#   This file is part of archify.

#   archify is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   archify is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with archify.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Create ~/.ssh/login-keys.d/
  tags: credentials
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/.ssh/keys.d"
    - "{{ ansible_user_dir }}/.ssh/login-keys.d"
    - "{{ ansible_user_dir }}/.ssh/session-keys.d"

- name: Set credentials for main user
  tags: credentials
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    password: "{{ user_password | mandatory }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/keys.d/id_ed25519
    ssh_key_passphrase: "{{ user_passphrase | mandatory }}"

- name: Symlink ~/.ssh/login-keys.d/id_ed25519 to ~/.ssh/keys.d/id_ed25519
  tags: credentials
  file:
    src: "../keys.d/id_ed25519"
    path: "{{ ansible_user_dir }}/.ssh/login-keys.d/id_ed25519"
    state: link
