---
- name: Install git and tig
  pacman:
    name={{ item }}
    state=installed
  with_items:
    - git
    - tig


- name: Install gitflow-avh
  command:
    yaourt --noconfirm -S {{ item }}
  register: yaourt_result
  changed_when: "yaourt_result.stderr != ''"
  with_items:
    - gitflow-avh
    - bash-completion-gitflow-avh
  sudo: no

- name: Gather facts to refreash ansible_env
  sudo: no
  setup:

- name: Configure git
  sudo: no
  template:
    src={{ item }}.j2
    dest={{ ansible_env.HOME }}/{{ item }}
  with_items:
    - .gitconfig
