---
- name: Install git, tig, gitg, gti, hub and gitflow
  tags: git
  aur:
    skip_installed: yes
    name:
      - git
      - tig
      - gitg
      - gti
      - hub
      - gitflow-avh
      - gitflow-fishcompletion-avh

- name: Configure git
  tags: git
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  loop:
    - .gitconfig

- name: Install helper scripts
  tags: git
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: preserve
  with_fileglob: "*"
