---
- name: Install git, tig and gitg
  tags:
    - git
    - tig
  pacman:
    name:
      - git
      - tig
      - gitg

- name: Install gitflow-avh
  become: no
  aur:
    name:
      - gitflow-avh
      - gitflow-fishcompletion-avh
    skip_installed: yes
  tags:
    - git
    - gitflow

- name: Gather facts to refresh ansible_env
  become: no
  setup:
  tags:
   - git

- name: Configure git
  become: no
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  loop:
    - .gitconfig
  tags:
    - git
