---
- name: Install git and tig
  pacman:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - tig

- name: Install gitflow-avh
  command:
    yaourt --noconfirm -S {{ item }}
  register: yaourt_result
  changed_when: "yaourt_result.stderr != ''"
  with_items:
    - gitflow-avh
    - gitflow-fishcompletion-avh
  become: no
  tags:
    - git
    - gitflow

- name: Gather facts to refreash ansible_env
  become: no
  setup:
  tags:
   - git

- name: Configure git
  become: no
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  with_items:
    - .gitconfig
  tags:
    - git
