---
- name: Install git and tig
  pacman:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - tig

- name: Install gitflow-avh
  become: no
  aur:
    name:
      - gitflow-avh
      - gitflow-fishcompletion-avh
    skip_installed: yes
  tags:
    - git
    - gitflow

- name: Gather facts to refresh ansible_env
  become: no
  setup:
  tags:
   - git

- name: Configure git
  become: no
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .gitconfig
  tags:
    - git
