- name: Create ESP filesystem
  tags: filesystem
  filesystem:
    dev: "{{ filesystems_esp_volume }}"
    fstype: vfat
    opts: -F32 -nESP
    force: yes

- name: Create swap volume
  tags: mkswap
  command:
    mkswap -L swap "{{ filesystems_swap_volume }}"

- name: Create BTRFS filesystem
  tags: mkbtrfs
  filesystem:
    dev: "{{ filesystems_root_volume }}"
    fstype: btrfs
    force: yes
    opts: -L root
