---
- name: Install wpa_supplicant
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - wpa_supplicant
  tags:
    - wpa_supplicant

- name: Install wpa_supplicant_gui
  become: no
  command: >
    yaourt -S --noconfirm wpa_supplicant_gui

- name: Install wpa_supplicant-wlan0.conf
  template:
    src: "{{ item.template }}"
    dest: /etc/wpa_supplicant/{{ item.dest }}
    backup: yes
    owner: root
    group: root
    mode: 0600
  with_items:
    - "{{ config_file }}"
  notify:
    - Restart wpa_supplicant@wlan0.service
  tags:
    - wpa_supplicant

- name: Enable wpa_supplicant@wlan0.service
  service:
    name: "{{ service_name }}"
    enabled: yes
    state: started
  failed_when: false
  tags:
    - wpa_supplicant
    - DEBUG
