---
- name: Assert that wifi_device is defined
  assert:
    that: "wifi_device is defined"
    msg: "'wifi_device' must be defined"

- name: Install wpa_supplicant
  pacman:
    name: wpa_supplicant
  tags:
    - wpa_supplicant

- name: Install wpa_supplicant_gui
  become: no
  aur:
    name: wpa_supplicant_gui
    skip_installed: yes

- name: Install wpa_supplicant-{{ wifi_device }}.conf
  template:
    src: "{{ item.template }}"
    dest: /etc/wpa_supplicant/{{ item.dest }}
    backup: yes
    owner: root
    group: root
    mode: 0600
  loop:
    - "{{ config_file }}"
  notify:
    - Restart wpa_supplicant@wlan0.service
  tags:
    - wpa_supplicant

- name: Enable wpa_supplicant@{{ wifi_device }}.service
  service:
    name: "{{ service_name }}"
    enabled: yes
    state: started
  ignore_errors: yes
  tags:
    - wpa_supplicant
    - DEBUG
