---
- name: Install OpenSC, ca-certificates-{fnmt,dnie} and friends
  tags: opensc
  aur:
    skip_installed: yes
    name:
      - opensc
      - ccid
      - pcsc-tools
      - ca-certificates-utils
      - ca-certificates-fnmt
      - ca-certificates-dnie

- name: Enable pcscd.service
  tags: opensc
  become: yes
  service:
    name: pcscd
    enabled: yes
    state: started
