---
dependencies:
    - hostname
    - sudo
    - udev
    - pacman
    - dhcpcd
    - dnsmasq
    - netctl
    - ntp
    - openssh
    - bluetooth
    - initcpio
    - locale
    - localtime
    - readline
    - vconsole
    - xorg
    - xdm
    - spectrwm
    - libvirt
    - mlocate
    - nginx
