# Copyright © 2019 4km3
# https://github.com/orgs/4km3/people

#   This file is part of archify.

#   archify is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   archify is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with archify.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: GPL-3.0-or-later
---
dependencies:
    - pacman
    - aur
    - intel
    - { role: broadcom, when: has_broadcom is defined and has_broadcom }
    - udev
    - hostname
    - sudo
    - systemd-networkd
    - systemd-resolved
    - systemd-timesyncd
    - openssh
    - { role: opensc, when: want_opensc is defined and want_opensc }
    - { role: bluetooth, when: has_bt is defined and has_bt }
    - { role: macfanctld, when: is_mac is defined and is_mac }
    - { role: ddclient, when: want_ddclient is defined and want_ddclient }
    - initcpio
    - locale
    - localtime
    - readline
    - vconsole
    - alsa
    - { role: mpd, when: want_mpd is defined and want_mpd }
    - xorg
    - xdm
    - spectrwm
    - unclutter
    - xcape
    - xdg
    - mpv
    - xbindkeys
    - pam_ssh
    - { role: libvirt, when: want_libvirt is defined and want_libvirt }
    - { role: docker, when: want_docker is defined and want_docker }
    - mlocate
    - pkgfile
    - { role: spacemacs, when: want_emacs is defined and want_emacs }
    - { role: golang, when: want_golang is defined and want_golang }
    - bash
    - fish
    - { role: todotxt, when: want_todotxt is defined and want_todotxt }
    - { role: ansible, when: want_ansible is defined and want_ansible }
