---
dependencies:
    - broadcom
    - hostname
    - sudo
    - udev
    - pacman
    - systemd-networkd
    - systemd-resolved
    - systemd-timesyncd
    - openssh
    - bluetooth
    - initcpio
    - locale
    - localtime
    - readline
    - vconsole
    - alsa
    - xorg
    - xdm
    - spectrwm
    - pam_ssh
    - vimperator
    - flashplugin
    - libvirt
    - mlocate
    - nginx
