---
dependencies:
    - intel
    - broadcom
    - hostname
    - sudo
    - udev
    - pacman
    - systemd-networkd
    - systemd-resolved
    - systemd-timesyncd
    - openssh
    - { role: bluetooth, when: has_bt is defined and has_bt }
    - { role: macfanctld, when: is_mac is defined and is_mac }
    - initcpio
    - locale
    - localtime
    - readline
    - vconsole
    - alsa
    - xorg
    - xdm
    - spectrwm
    - unclutter
    - xdg
    - mpv
    - xbindkeys
    - pam_ssh
    - pentadactyl
    - libvirt
    - docker
    - mlocate
    - pkgfile
    - nginx
    - spacemacs
    - bash
    - fish
    - yay
