---
dependencies:
    - pacman
    - aur
    - intel
    - { role: broadcom, when: has_broadcom is defined and has_broadcom }
    - hostname
    - sudo
    - systemd-networkd
    - systemd-resolved
    - systemd-timesyncd
    - openssh
    - { role: opensc, when: want_opensc is defined and want_opensc }
    - { role: bluetooth, when: has_bt is defined and has_bt }
    - { role: macfanctld, when: is_mac is defined and is_mac }
    - initcpio
    - locale
    - localtime
    - readline
    - vconsole
    - alsa
    - { role: mpd, when: want_mpd is defined and want_mpd }
    - xorg
    - xdm
    - spectrwm
    - unclutter
    - xdg
    - mpv
    - xbindkeys
    - pam_ssh
    - { role: libvirt, when: want_libvirt is defined and want_libvirt }
    - { role: docker, when: want_docker is defined and want_docker }
    - mlocate
    - pkgfile
    - { role: spacemacs, when: want_emacs is defined and want_emacs }
    - { role: golang, when: want_golang is defined and want_golang }
    - bash
    - fish
    - { role: todotxt, when: want_todotxt is defined and want_todotxt }
    - { role: ansible, when: want_ansible is defined and want_ansible }
