---
dependencies:
    - aur
    - intel
    - { role: broadcom, when: has_broadcom is defined and has_broadcom }
    - hostname
    - sudo
    - pacman
    - systemd-networkd
    - systemd-resolved
    - systemd-timesyncd
    - openssh
    - opensc
    - { role: bluetooth, when: has_bt is defined and has_bt }
    - { role: macfanctld, when: is_mac is defined and is_mac }
    - initcpio
    - locale
    - localtime
    - readline
    - vconsole
    - alsa
    - mpd
    - xorg
    - xdm
    - spectrwm
    - unclutter
    - xdg
    - mpv
    - xbindkeys
    - pam_ssh
    - libvirt
    - docker
    - mlocate
    - pkgfile
    - spacemacs
    - golang
    - bash
    - fish
    - todotxt
    - ansible
