---
- name: Install todotxt.com
  tags: todotxt
  aur:
    name: todotxt
    skip_installed: yes

- name: Gather facts to refresh ansible_env
  tags: todotxt
  setup:

- name: Install helper scripts
  tags: todotxt
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.config/fish/functions/{{ item }}"
  loop:
    - t.fish
    - ct.fish
    - ut.fish
    - pusht.fish

# - name: TODO add TODO var pointing to ~/.todo
#   tags: todotxt
#   setup:

# - name: Clone todo.git
#   tags: todotxt
#   git:
#     repo: "{{ todotxt_repo }}"
#     dest: "{{ ansible_user_dir }}/.todo"
