# Copyright © 2019 4km3
# https://github.com/orgs/4km3/people

#   This file is part of archify.

#   archify is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   archify is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with archify.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install todotxt.com
  tags: todotxt
  aur:
    name: todotxt

- name: Install helper scripts
  tags: todotxt
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.config/fish/functions/{{ item }}"
  loop:
    - t.fish
    - ct.fish
    - ut.fish
    - pusht.fish

# - name: TODO add TODO var pointing to ~/.todo
#   tags: todotxt
#   setup:

# - name: Clone todo.git
#   tags: todotxt
#   git:
#     repo: "{{ todotxt_repo }}"
#     dest: "{{ ansible_user_dir }}/.todo"
