---
- name: Create symlink from /dev/null to /etc/udev/rules.d/80-net-setup-link.rules
  tags: udev
  become: yes
  file:
    src: /dev/null
    path: /etc/udev/rules.d/80-net-setup-link.rules
    state: link
  when: want_unpredictable_kernel_names is defined and want_unpredictable_kernel_names

- name: Install udev rules
  tags: udev
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/udev/rules.d/{{ item }}
  loop:
    - zz-usb_storage.rules
    - zz-usb_media.rules
