#!/usr/bin/env sh

START="${1:-HEAD^}"

git filter-branch							\
	--commit-filter '						\
		export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME";		\
		export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL";		\
		export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE";		\
		git commit-tree "$@"'					\
	-- ${START}..HEAD
