---
- name: Install spectrwm, rofi, scrot and slock
  tags: spectrwm
  become: no
  aur:
    skip_installed: yes
    name:
      - spectrwm
      - rofi
      - scrot
      - slock

- name: Configure spectrwm
  tags: spectrwm
  become: yes
  template:
    src: spectrwm.conf.j2
    dest: /etc/spectrwm.conf

- name: Enable screenshot.sh
  tags: spectrwm
  become: yes
  file:
    src: /usr/share/spectrwm/{{ item }}
    path: /usr/local/bin/{{ item }}
    state: link
  loop:
    - screenshot.sh

- name: Enable spectrwm
  tags: spectrwm
  become: yes
  copy:
    content: "exec spectrwm\n"
    dest: /etc/X11/xinit/xinitrc.d/99-spectrwm.sh
    owner: root
    group: root
    mode: 0755

- name: Create rofi config dir
  tags: rofi
  become: no
  file:
    path: "{{ ansible_user_dir }}/.config/rofi"
    state: directory

- name: Configure rofi theme
  tags: rofi
  become: no
  copy:
    content: "rofi.theme: /usr/share/rofi/themes/glue_pro_blue.rasi\n"
    dest: "{{ ansible_user_dir }}/.config/rofi/config"
